### ISSUE TITLE
Marshaling ref struct for return value

### ISSUE THREAD

**Issue by BlackCentipede** [Firwood-Software/AdvanceDLSupport#62]
Linux OS: Arch Linux (Latest Update Nov-27-2018)
Dotnet Version: 2.1.500
Clang: 7.0.0
Compile CLI for C: clang -std=c99 -fPIC -shared -olibChapSix.so ChapSix.c
ADL Version: 2.3.0 (From Nuget)

The problem is that Ref Struct does not seem to be supported for return value when defined in interface:

C File: (ChapSix.c -> libChapSix.so via Clang)
```c
typedef struct
{
    char StringData[128];
} ByValString;

ByValString* Initialize()
{
    return (ByValString*)malloc(sizeof(ByValString));
}
```

C# File:
```cs
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
public struct ByValString
{
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
    public string String_ByValTStr;
}

public unsafe interface IChapSixLib
{
    ref ByValString Initialize();
}

public class Program
{
    static void Main(string[] args)
    {
        var lib = NativeLibraryBuilder.Default.ActivateInterface<IChapSixLib>("ChapSix");
        var result = lib.Initialize();
    }
}

```
CSProj File Content (Including Build Target):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdvancedDLSupport" Version="2.3.0" />
  </ItemGroup>
  <Target Name="CompileCProject" AfterTargets="AfterBuild">
    <exec Command="clang -std=c99 -shared -fPIC -olibChapSix.so ChapSix.c" />
    <Copy SourceFiles="libChapSix.so" DestinationFolder="$(OutDir)" />
  </Target>
</Project>

```

The stacktrace:
```
Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'return value': Invalid managed/unmanaged type combination.
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateClass(String libraryPath, Type baseClassType, Type[] interfaceTypes) in /home/jarl/Programming/AdvanceDLSupport/AdvancedDLSupport/NativeLibraryBuilder.cs:line 338
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateClass[TClass,TInterface](String libraryPath) in /home/jarl/Programming/AdvanceDLSupport/AdvancedDLSupport/NativeLibraryBuilder.cs:line 257
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateInterface[TInterface](String libraryPath) in /home/jarl/Programming/AdvanceDLSupport/AdvancedDLSupport/NativeLibraryBuilder.cs:line 191
   at Program.Main(String[] args) in /home/centi/Projects/Tutorials/ChapterSix/Program.cs:line 48
```

**Comment by BlackCentipede** [comment]
Tired from last night, so closing this issue.
